# Redis Configuration
port 6379
bind 127.0.0.1
databases 16
maxmemory 512mb
maxmemory-policy allkeys-lru
timeout 300
tcp-keepalive 60
loglevel notice
logfile ""
save 900 1
save 300 10
save 60 10000
rdbcompression yes
rdbchecksum yes
dbfilename dump.rdb
dir ./
appendonly yes
appendfilename "appendonly.aof"
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
